/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SmartHome;


import java.sql.*;
import Lib.Source;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;

public class Tables extends javax.swing.JFrame {

    ResultSet rs = null;
    Connection conn = null;
    Statement stmt = null;
    
    int userSelectTable = 0;
   List<String> list = new ArrayList<String>();
   Map<Object,List<Object>> dataMap = new LinkedHashMap<>();
   
   JTable table;
   CardLayout card;
   JPanel cardPane;
   
    public Tables() {
        initComponents();
        Display();
                        
    }
    
    public void Display(){
              try {
            Class.forName(Source.driver);
            conn = DriverManager.getConnection(Source.url,Source.userName,Source.password);
            stmt = conn.createStatement();

            DatabaseMetaData dbmd = conn.getMetaData();
            
            String[] types = {"TABLE"};
            ResultSet rs = dbmd.getTables("testDb", null, "%", types);
            while (rs.next()) {
                if(!rs.getString("TABLE_NAME").toString().equals("developeroption")){
                    System.out.println(rs.getString("TABLE_NAME"));
                comboTable.addItem(rs.getString("TABLE_NAME"));      
                }
            }         
        }catch (Exception e) {
           JOptionPane.showMessageDialog(this,e.toString());
        }
    }
    
    private void deleteTable(){
      try {
            Class.forName(Source.driver);
            conn = DriverManager.getConnection(Source.url,Source.userName,Source.password);
            stmt = conn.createStatement();

            stmt.execute("drop table "+comboTable.getSelectedItem().toString()+"");
            JOptionPane.showMessageDialog(this,"Delete Table Success");
            //comboTable.setSelectedIndex(0);
            Display();
            
        }catch (Exception e) {
           JOptionPane.showMessageDialog(this,e.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pp1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCreateTable = new javax.swing.JButton();
        comboTable = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnShow = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnInsertData = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pp1.setBackground(new java.awt.Color(255, 153, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Tables");

        btnCreateTable.setBackground(new java.awt.Color(0, 0, 0));
        btnCreateTable.setForeground(new java.awt.Color(255, 255, 255));
        btnCreateTable.setText("CREATE NEW TABLE");
        btnCreateTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateTableActionPerformed(evt);
            }
        });

        comboTable.setBackground(new java.awt.Color(255, 255, 255));
        comboTable.setForeground(new java.awt.Color(255, 255, 255));
        comboTable.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Table" }));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Tables");

        btnShow.setBackground(new java.awt.Color(0, 0, 0));
        btnShow.setForeground(new java.awt.Color(255, 255, 255));
        btnShow.setText("SHOW TABLE");
        btnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(0, 0, 0));
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(0, 0, 0));
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("EDIT TABLE");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnInsertData.setBackground(new java.awt.Color(0, 0, 0));
        btnInsertData.setForeground(new java.awt.Color(255, 255, 255));
        btnInsertData.setText("INSERT DATA");
        btnInsertData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pp1Layout = new javax.swing.GroupLayout(pp1);
        pp1.setLayout(pp1Layout);
        pp1Layout.setHorizontalGroup(
            pp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pp1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(pp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pp1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pp1Layout.createSequentialGroup()
                        .addGroup(pp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pp1Layout.createSequentialGroup()
                                .addComponent(comboTable, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnShow)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                                .addComponent(btnInsertData)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pp1Layout.createSequentialGroup()
                                .addGroup(pp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(btnCreateTable))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(36, 36, 36))
                    .addGroup(pp1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pp1Layout.setVerticalGroup(
            pp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pp1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnInsertData, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pp1Layout.createSequentialGroup()
                        .addGroup(pp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCreateTable, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(pp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(comboTable, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnShow, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(213, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pp1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pp1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateTableActionPerformed
       CreateTable ct = new CreateTable();
       this.setVisible(false);
       ct.setVisible(true);
    }//GEN-LAST:event_btnCreateTableActionPerformed

    private void btnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowActionPerformed
       dataMap.clear();
       list.clear();
      try{
          cardPane.removeAll();
      }catch(Exception e){
          System.out.println("no card in panel");
      }
      int count  = 0;
        if(comboTable.getSelectedIndex() != 0){
           userSelectTable = comboTable.getSelectedIndex();
               try{
             Class.forName(Source.driver);
             conn = DriverManager.getConnection(Source.url,Source.userName,Source.password);
             stmt = conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_READ_ONLY);
             
             String tableName = comboTable.getSelectedItem().toString();    
               
              String sql = "select * from "+tableName+""; 
              
             rs = stmt.executeQuery(sql);
              ResultSetMetaData resultSetMetaData = rs.getMetaData();
             int columnCount = resultSetMetaData.getColumnCount();
             
             System.out.println("column count " + columnCount);
             
             for(int i=1;i<=columnCount;i++){
                 String name = resultSetMetaData.getColumnName(i);
                 if(name != null){
                     list.add(name);
                 }
             }         
             while(rs.next()){
                 List<Object> list = new ArrayList<Object>();
                  for(int i=1;i<=columnCount;i++){
                      Object name = rs.getObject(i);
                          list.add(name);
                      dataMap.put(list.get(0), list);
                  }  
             }  
                    Object[][] data = new Object[dataMap.size()][columnCount];
                 
                    Set<Object> nameOfType = dataMap.keySet();
                    List<Object> nameList = new ArrayList<Object>(nameOfType);

                    for(int i=0;i<data.length;i++){
                         data[i] = dataMap.get(nameList.get(i)).toArray();    
                    }

                   if(comboTable.getSelectedIndex() != 0){
                        table = new JTable(data,list.toArray());
                        table.setRowSelectionAllowed(true);
                        
                        table.setBounds(30,200,600,160);                         
                         JScrollPane jScroll = new JScrollPane(table);
                        jScroll.setBounds(30,200,600,160);
                        
                        cardPane = new JPanel();
                        card = new CardLayout();
                        cardPane.setBounds(30,200,600,160);
                        cardPane.setLayout(card);
                        cardPane.add(jScroll);
                        
                        pp1.add(cardPane);
                        card.last(cardPane);                       
                       this.setVisible(true); 
                   }   
               }catch(Exception e){
                  System.err.println(e.getMessage());
               }
            }
    }//GEN-LAST:event_btnShowActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        Home h = new Home();
        this.setVisible(false);
        h.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
       if(comboTable.getSelectedIndex() != 0){
          
        Source.tableTable = comboTable.getSelectedItem().toString();
        //System.out.println("table name check "+Source.tableTable);
           
           EditTable et = new EditTable();
           this.setVisible(false);
           et.setVisible(true);
           
       }else{
           JOptionPane.showMessageDialog(this,"Please select one table in combo box!");
       }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnInsertDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertDataActionPerformed
        if(comboTable.getSelectedIndex() != 0){
            if(comboTable.getSelectedItem().toString() != "client" && 
               comboTable.getSelectedItem().toString() != "item" &&
               comboTable.getSelectedItem().toString()!= "login"){
               Source.tableTable = comboTable.getSelectedItem().toString();
                CRUDTable crudt = new CRUDTable();
                this.setVisible(false);
                crudt.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(this,"\"Client\",\"Item\",\"Login\" tables are allow  only in their section to change data ");
            }
        }else{
            JOptionPane.showMessageDialog(this,"Please select one table in combo box!");
        }
    }//GEN-LAST:event_btnInsertDataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tables.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tables().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreateTable;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnInsertData;
    private javax.swing.JButton btnShow;
    private javax.swing.JComboBox<String> comboTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel pp1;
    // End of variables declaration//GEN-END:variables
}
